/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import static classes.Outgoing.jLabel_balance1;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author wayomi
 */
public class credit extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    public credit() {
        initComponents();
        this.setLocationRelativeTo(this);
        con = DBConnect.connect();        
        jTable1.setAutoCreateRowSorter(true);
        update_table();
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        pack();
        jLabel_creditBal.setText("0.00");
    }
    public void update_table()
    {
            
        try {
            String sql = "select date AS 'DATE', Name AS 'NAME', amount AS 'AMOUNT',card AS 'CARD',cash AS 'CASH',type AS 'PAYMENT TYPE',"
                    + "balance AS 'BALANCE' FROM credit"; 
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            JTableHeader head = jTable1.getTableHeader();
            head.setForeground(Color.blue);            
            jTable1.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 11));
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
        } 
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        heading = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        slide = new javax.swing.JPanel();
        jLabel_dashboard = new javax.swing.JLabel();
        jLabel_Income = new javax.swing.JLabel();
        jLabel_outgoing = new javax.swing.JLabel();
        jLabel_reports = new javax.swing.JLabel();
        jLabel_staff = new javax.swing.JLabel();
        jLabel_vendor = new javax.swing.JLabel();
        jLabel_vendor1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField_name = new javax.swing.JTextField();
        jTextField_amt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField_payment = new javax.swing.JTextField();
        jLabel_creditBal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel_paid = new javax.swing.JLabel();
        card_radio = new javax.swing.JRadioButton();
        cash_Radio = new javax.swing.JRadioButton();
        jLabel_paid1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1172, 745));
        setPreferredSize(new java.awt.Dimension(1172, 745));

        heading.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("IOM - Income~Outgoing Manager - Credit");

        javax.swing.GroupLayout headingLayout = new javax.swing.GroupLayout(heading);
        heading.setLayout(headingLayout);
        headingLayout.setHorizontalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headingLayout.setVerticalGroup(
            headingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        slide.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_dashboard.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_dashboard.setText("Dashboard");
        jLabel_dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
        });

        jLabel_Income.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_Income.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_Income.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Income.setText("Income");
        jLabel_Income.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_IncomeMouseClicked(evt);
            }
        });

        jLabel_outgoing.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_outgoing.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_outgoing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_outgoing.setText("Outgoing");
        jLabel_outgoing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_outgoingMouseClicked(evt);
            }
        });

        jLabel_reports.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_reports.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_reports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_reports.setText("Reports");
        jLabel_reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_reportsMouseClicked(evt);
            }
        });

        jLabel_staff.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_staff.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_staff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_staff.setText("Staff");
        jLabel_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_staffMouseClicked(evt);
            }
        });

        jLabel_vendor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_vendor.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_vendor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_vendor.setText("New Vendor");
        jLabel_vendor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_vendorMouseClicked(evt);
            }
        });

        jLabel_vendor1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel_vendor1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_vendor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_vendor1.setText("Credit");
        jLabel_vendor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_vendor1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout slideLayout = new javax.swing.GroupLayout(slide);
        slide.setLayout(slideLayout);
        slideLayout.setHorizontalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(jLabel_Income, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_outgoing, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_reports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_vendor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_vendor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideLayout.setVerticalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideLayout.createSequentialGroup()
                .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Income, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_outgoing, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_vendor1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 210, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("DATE");

        jLabel2.setText("NAME");

        jLabel3.setText("AMOUNT");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("PAYMENT TYPE");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT METHOD", "CASH", "CARD", "NOT PAID" }));

        jLabel5.setText("PAYMENT");

        jTextField_payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_paymentKeyReleased(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(card_radio);
        card_radio.setText("CARD");
        card_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(cash_Radio);
        cash_Radio.setText("CASH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jTextField_name)
                    .addComponent(jTextField_amt)
                    .addComponent(jTextField_payment))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_creditBal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_paid1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(card_radio)
                .addGap(44, 44, 44)
                .addComponent(cash_Radio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_paid1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField_amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_creditBal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(card_radio)
                    .addComponent(cash_Radio))
                .addGap(37, 37, 37))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_IncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_IncomeMouseClicked
        Income i = new Income();
        i.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel_IncomeMouseClicked

    private void jLabel_outgoingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_outgoingMouseClicked
        Outgoing o = new Outgoing();
        o.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel_outgoingMouseClicked

    private void jLabel_reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_reportsMouseClicked
        Reports r = new Reports();
        r.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel_reportsMouseClicked

    private void jLabel_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_staffMouseClicked
        newVendor v = new newVendor();
        v.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel_staffMouseClicked

    private void jLabel_vendorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_vendorMouseClicked
        vendor v = new vendor();
        v.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel_vendorMouseClicked

    private void jLabel_vendor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_vendor1MouseClicked
            credit c = new credit();
            c.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_jLabel_vendor1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel_paid1.setText("0.00");
        jLabel_paid.setText("0.00");
        
        if(card_radio.isSelected()){
            try {
             String sql = "insert into credit (date,Name,amount,type, card,balance) "
                     + "values (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            String date = sdf.format(jDateChooser1.getDate());
            pst.setString(1,date);            
            pst.setString(2, jTextField_name.getText());
            pst.setString(3,jTextField_amt.getText());
             String method = jComboBox1.getSelectedItem().toString();
            pst.setString(4, method);             
            pst.setString(5, jTextField_payment.getText());
            pst.setString(6, jLabel_creditBal.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully..!!");
            
            update_table();
            jTextField_amt.setText("");
            jTextField_name.setText("");
            jLabel_creditBal.setText("");
            jTextField_payment.setText("");
            jDateChooser1.setDate(null);
            jLabel_paid.setText("");
            jLabel_paid1.setText("");
            cash_Radio.setSelected(false);
            card_radio.setSelected(false);
                        
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
         if(cash_Radio.isSelected())
         {
             try {
             String sql = "insert into credit (date,Name,amount,type, cash,balance) "
                     + "values (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            String date = sdf.format(jDateChooser1.getDate());
            pst.setString(1,date);            
            pst.setString(2, jTextField_name.getText());
            pst.setString(3,jTextField_amt.getText());
             String method = jComboBox1.getSelectedItem().toString();
            pst.setString(4, method);             
            pst.setString(5, jTextField_payment.getText());
            pst.setString(6, jLabel_creditBal.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully..!!");
            
            update_table();
            jTextField_amt.setText("");
            jTextField_name.setText("");
            jLabel_creditBal.setText("");
            jTextField_payment.setText("");
            jDateChooser1.setDate(null);
            jLabel_paid.setText("");
            jLabel_paid1.setText("");
            cash_Radio.setSelected(false);
            card_radio.setSelected(false);
                        
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
             
         }
        }
        else{
        try {
             String sql = "insert into credit (date,Name,amount,type, payment,balance) "
                     + "values (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            String date = sdf.format(jDateChooser1.getDate());
            pst.setString(1,date);            
            pst.setString(2, jTextField_name.getText());
            pst.setString(3,jTextField_amt.getText());
             String method = jComboBox1.getSelectedItem().toString();
            pst.setString(4, method);             
            pst.setString(5, jTextField_payment.getText());
            pst.setString(6, jLabel_creditBal.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted Successfully..!!");
            
            update_table();
            jTextField_amt.setText("");
            jTextField_name.setText("");
            jLabel_creditBal.setText("");
            jTextField_payment.setText("");
            jDateChooser1.setDate(null);
            jLabel_paid.setText("");
            jLabel_paid1.setText("");
            cash_Radio.setSelected(false);
            card_radio.setSelected(false);
                        
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_paymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_paymentKeyReleased
         try {
            double amt = Float.parseFloat(jTextField_amt.getText());
            double paid = Float.parseFloat(jTextField_payment.getText());

            double balance = amt - paid;
            String v1 = String.format("%.2f", balance);
            jLabel_creditBal.setText(v1 + "");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField_paymentKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         try {

            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int i = jTable1.getSelectedRow();

            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) jTable1.getValueAt(i,0));
            jDateChooser1.setDate(date);
            jTextField_name.setText(jTable1.getValueAt(i, 1).toString());
            //jTextField_amt.setText(model.getValueAt(i, 2).toString());
            //jTextField_payment.setText(model.getValueAt(i, 3).toString());            
            jComboBox1.getModel().setSelectedItem(jTable1.getValueAt(i,5));   
            jTextField_amt.setText(jTable1.getValueAt(i, 6).toString());
            jLabel_paid.setText(jTable1.getValueAt(i, 3).toString());
            jLabel_paid1.setText(jTable1.getValueAt(i, 4).toString());
            
        } catch (ParseException ex) {
            //Logger.getLogger(Income.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel_paid1.setText("0.00");
        jLabel_paid.setText("0.00");
        
        if(cash_Radio.isSelected())
        {
        try {
            int row = jTable1.getSelectedRow();
                String id = jTable1.getModel().getValueAt(row, 1).toString();
                String sql = "UPDATE credit SET date=?,"
                + "Name=?,"
                + "type=?,cash = ?,balance=? WHERE Name = '" + id +"' ";
                pst = con.prepareStatement(sql);
                String date = sdf.format(jDateChooser1.getDate());
                pst.setString(1,date);
                pst.setString(2, jTextField_name.getText());            
                String method = jComboBox1.getSelectedItem().toString();
                pst.setString(3, method); 
                double val1 = 0.00;
                val1 = Float.parseFloat(jLabel_paid1.getText());
                Float val2 = Float.parseFloat(jTextField_payment.getText());
                Double val = val1 + val2;
                pst.setString(4, val.toString());
                pst.setString(5, jLabel_creditBal.getText());
                
                pst.executeUpdate();
            
                update_table();

            JOptionPane.showMessageDialog(null,"Updated Successfully..!!"); 
            
            jTextField_amt.setText("");
            jTextField_name.setText("");   
            jLabel_creditBal.setText("");
            jTextField_payment.setText("");
            jDateChooser1.setDate(null);
            jLabel_paid.setText("");
            jLabel_paid1.setText("");
            cash_Radio.setSelected(false);
            card_radio.setSelected(false);
            
        } 
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,e); 
        }
        }
        if(card_radio.isSelected())
        {
        try {
            int row = jTable1.getSelectedRow();
                String id = jTable1.getModel().getValueAt(row, 1).toString();
                String sql = "UPDATE credit SET date=?,"
                + "Name=?,"
                + "type=?,card = ?,balance=? WHERE Name = '" + id +"' ";
                pst = con.prepareStatement(sql);
                String date = sdf.format(jDateChooser1.getDate());
                pst.setString(1,date);
                pst.setString(2, jTextField_name.getText());            
                String method = jComboBox1.getSelectedItem().toString();
                pst.setString(3, method); 
                Float val1 = Float.parseFloat(jLabel_paid.getText());
                Float val2 = Float.parseFloat(jTextField_payment.getText());
                Float val = val1 + val2;
                pst.setString(4, val.toString());
                pst.setString(5, jLabel_creditBal.getText());
                
                pst.executeUpdate();
            
                update_table();

            JOptionPane.showMessageDialog(null,"Updated Successfully..!!"); 
            
            jTextField_amt.setText("");
            jTextField_name.setText("");   
            jLabel_creditBal.setText("");
            jTextField_payment.setText("");
            jDateChooser1.setDate(null);
            jLabel_paid.setText("");
            jLabel_paid1.setText("");
            cash_Radio.setSelected(false);
            card_radio.setSelected(false);
            
        } 
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,e); 
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField_amt.setText("");
            jTextField_name.setText("");            
            jLabel_creditBal.setText("");
            jTextField_payment.setText("");
            jDateChooser1.setDate(null);
            jLabel_paid.setText("");
            jLabel_paid1.setText("");
            cash_Radio.setSelected(false);
            card_radio.setSelected(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            
            int row = jTable1.getSelectedRow();
            String id = jTable1.getModel().getValueAt(row, 1).toString();
            String sql = "DELETE FROM credit where Name = '" + id + "'";
            pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted Succesfully..!!");
            
            update_table();
            
            jTextField_amt.setText("");
            jTextField_name.setText("");           
            jLabel_creditBal.setText("");
            jTextField_payment.setText("");
            jDateChooser1.setDate(null);
            jLabel_paid.setText("");
            jLabel_paid1.setText("");
            cash_Radio.setSelected(false);
            card_radio.setSelected(false);
           
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseClicked
        Home h = new Home();
        h.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel_dashboardMouseClicked

    private void card_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card_radioActionPerformed
        
    }//GEN-LAST:event_card_radioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new credit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton card_radio;
    private javax.swing.JRadioButton cash_Radio;
    private javax.swing.JPanel heading;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Income;
    public static javax.swing.JLabel jLabel_creditBal;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_outgoing;
    private javax.swing.JLabel jLabel_paid;
    private javax.swing.JLabel jLabel_paid1;
    private javax.swing.JLabel jLabel_reports;
    private javax.swing.JLabel jLabel_staff;
    private javax.swing.JLabel jLabel_vendor;
    private javax.swing.JLabel jLabel_vendor1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_amt;
    public static javax.swing.JTextField jTextField_name;
    public static javax.swing.JTextField jTextField_payment;
    private javax.swing.JPanel slide;
    // End of variables declaration//GEN-END:variables
}
